# Generated by Django 4.1.4 on 2023-01-13 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lista_usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='edad',
            field=models.FloatField(),
        ),
    ]
